export { default as Home } from '@pages/Public/Home/home.jsx'
export { default as PublicLayout } from '@pages/Public/PublicLayout/publicLayout.jsx'
export { default as Lodging } from '@pages/Public/Lodging/lodging.jsx'
export { default as Lodgings } from '@pages/Public/Lodgings/lodgings.jsx'
export { default as Activities } from '@pages/Public/Activities/activities.jsx'
export { default as PublicRouter } from '@pages/Public/publicRouter.jsx'