services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cequejeveux
      MYSQL_DATABASE: booki
      MYSQL_USER: neoz
      MYSQL_PASSWORD: matrix
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: